[package]
name = "decstust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.2", features = ["v4"] }
rand = "0.4.6"
